version: '3.9'

networks:
    net:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.55.0/24
                  gateway: 192.168.55.1

services:
    php-fpm:
        build:
            context: ./docker/images/php-fpm
            dockerfile: Dockerfile
        container_name: api-task-manager-php-fpm
        networks:
            net:
                ipv4_address: 192.168.55.10
        tty: true
        volumes:
            - './:/var/www/html'

    web:
        image: nginx:latest
        container_name: api-task-manager-web
        volumes:
            - './:/var/www/html'
            - './docker/default.conf:/etc/nginx/conf.d/default.conf'
        networks:
            net:
                ipv4_address: 192.168.55.11
        ports:
            - '80:80'
        tty: true
        links:
            - php-fpm