#!/usr/bin/env bash

HOST_USER_ID=$(id -u "$(whoami)")
HOST_GROUP_ID=$(id -g "$(whoami)")

docker run                                      \
    --rm --interactive --tty                    \
    --user "${HOST_USER_ID}:${HOST_GROUP_ID}"   \
    --network api-task-manager_net              \
    --volume "$PWD":/var/www/html               \
    --workdir /var/www/html                     \
    api-task-manager.php-fpm                    \
    php vendor/bin/phpunit "$@"
